default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: vrg_online_development
  host: localhost

test:
  <<: *default
  database: vrg_online_test
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
